### ISSUE TITLE
[Reopen] Pull Request create Event triggered too early

### ISSUE THREAD

**Issue by lcwang** [Eernie/bitbucket-webhooks-plugin#123]
This problem has been reported and resolved in a previous ticket: https://github.com/Eernie/bitbucket-webhooks-plugin/issues/50
However, we are still seeing this problem, after upgrading the Bitbucket Webhooks plugin to 1.6.2.

Error description:
We use the bitbucket-webhooks-plugin to trigger jenkins builds for opened pull requests.
The first build for newly created pull requests will randomly fail during Jenkinsfile checkout:

> git fetch --no-tags --progress https://bitbucket.XXXXX.com/scm/XXX/web-apps.git +refs/pull-requests/7/from:refs/remotes/origin/PR-7
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --no-tags --progress https://bitbucket.XXXXX.com/scm/XXX/web-apps.git +refs/pull-requests/7/from:refs/remotes/origin/PR-7" returned status code 128:
stdout: 
stderr: fatal: Couldn't find remote ref refs/pull-requests/7/from
Unexpected end of command stream
> 

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2002
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1721)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:405)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:614)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:144)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:120)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:298)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Error cloning remote repo 'origin'

If we restart the build in jenkins it succeeds.

**Comment by casz** [comment]
What version of Bitbucket branch source plugin are you using?

**Comment by casz** [comment]
No what version of Bitbucket branch source plugin are you using in your Jenkins instance.

**Comment by casz** [comment]
If your not using Bitbucket Branch source plugin than I cannot help you.
As stated in https://github.com/Eernie/bitbucket-webhooks-plugin/issues/50#issuecomment-317351085
https://community.atlassian.com/t5/Bitbucket-questions/Re-Change-pull-request-refs-after-Commit-instead-of-after/qaq-p/194703/comment-id/6829#M6829

Nothing we can do on our end.
You could use the Bitbucket Branch source plugin cause they will call Can Merge to ensure it is buildable:

https://plugins.jenkins.io/cloudbees-bitbucket-branch-source
https://wiki.jenkins.io/display/JENKINS/Bitbucket+Branch+Source+Plugin

Version 2.2.12 (July 5, 2018)
JENKINS-45997 - BitBucket PRs failing to checkout on initial run after PR updated with new commits RESOLVED   Check mergability when retrieving pull requests
